### ISSUE TITLE
[Design][khochaynhalam] - Design tổng thể - khochaynhalam

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam/khochaynhalam.github.io#1]
Dear Designer

Anh cần em thiết kế cho anh một trang web cho dự án này bằng [FIGMA](https://www.figma.com/file/BMgH1CSWMBf6WeaG3Y4eXN/khochaynhalam.com).

Hãy chia ra các task nhỏ để anh giám sát tiến trình công việc em nhé

sau khi làm xong việc thì commit link vào file: Design/link.html

Please help me design it.

Thanks and Best Regards
TrungNhan

****
09/03/2020
****

Dear @Vi1309 

Hiện tại anh Minh đã chốt thiết kế cho dự án.
Em tham khảo [link](https://pocteamnhan.wixsite.com/mysite) này để thiết kế lại cho dự án này nhé.
Dựa vào thiết kế đó anh yêu cầu thiết kế lại, theo đó tùy biến nôi dung, chức năng.
cái nào cần thiết giữ lại. cái nào không cần thiết bỏ đi nhé em.
Deadline thay đổi: hết tháng này. Tức là ngày 31/3/2020 sẽ chốt tất cả với anh Minh vì thế tối thiểu ngày 20 phải hoàn thành tất cả và tiến hành gởi cho anh Minh review.
Trong thời gian đó sẽ code song song.
Chia việc cho các bạn làm.
Tạo các task con để chia nhỏ công việc làm cho hiệu quả.

**Dealine thiết kế trang home: 11/03/2020**

Thanks 
TrungNhan

****
20/03/2020
****

Dear @Vi1309 ,

Tới thời điểm hiện tại như đã bàn từ trước thì chúng ta sẽ tạm ngưng bước design để chuyển sang bước code, vì thế ở task design này anh đổi yêu cầu

Dựa vào trang web https://pocteamnhan.wixsite.com/mysite
Kết quả hiển thị ở: https://www.figma.com/file/BMgH1CSWMBf6WeaG3Y4eXN/khochaynhalam.com?node-id=0%3A1
Anh có các yêu cầu như sau:

- [ ] 1. Lấy tất cả các màu của trang web đó có để phục vụ việc code sau này (task #13 )
- [ ] 2. Chụp ảnh màn hình các trang và ghép lại vào từng màn hình (task #14 )
- [ ] 3. Chọn font chữ phù hợp để sử dụng cho việc code sau này (task #15 )

Em chủ động chia công việc cho các bạn làm để đẩy nhanh tiến độ nhé

Thanks & Best Regards
TrungNhan

**Comment by Vi1309** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Vi

**Comment by Vi1309** [comment]
Dear @khochaynhalam [Tuấn]

Em làm xong cái task này rồi anh xem giùm em được không

Thanks
 Vi

**Comment by nhanntdl** [comment]
Dear @Vi1309 

Hiện tại anh Minh đã chốt thiết kế cho dự án.
Em tham khảo [link](https://pocteamnhan.wixsite.com/mysite) này để thiết kế lại cho dự án này nhé.
Dựa vào thiết kế đó anh yêu cầu thiết kế lại, theo đó tùy biến nôi dung, chức năng.
cái nào cần thiết giữ lại. cái nào không cần thiết bỏ đi nhé em.
Deadline thay đổi: hết tháng này. Tức là ngày 31/3/2020 sẽ chốt tất cả với anh Minh vì thế tối thiểu ngày 20 phải hoàn thành tất cả và tiến hành gởi cho anh Minh review.
Trong thời gian đó sẽ code song song.
Chia việc cho các bạn làm.
Tạo các task con để chia nhỏ công việc làm cho hiệu quả.

**Dealine thiết kế trang home: 11/03/2020**

Thanks 
TrungNhan

**Comment by nhanntdl** [comment]
Dear @Vi1309 ,

Tới thời điểm hiện tại như đã bàn từ trước thì chúng ta sẽ tạm ngưng bước design để chuyển sang bước code, vì thế ở task design này anh đổi yêu cầu

Dựa vào trang web https://pocteamnhan.wixsite.com/mysite
Kết quả hiển thị ở: https://www.figma.com/file/BMgH1CSWMBf6WeaG3Y4eXN/khochaynhalam.com?node-id=0%3A1
Anh có các yêu cầu như sau:

- [ ] 1. Lấy tất cả các màu của trang web đó có để phục vụ việc code sau này (task #13 )
- [ ] 2. Chụp ảnh màn hình các trang và ghép lại vào từng màn hình (task #14 )
- [ ] 3. Chọn font chữ phù hợp để sử dụng cho việc code sau này (task #15 )

Em chủ động chia công việc cho các bạn làm để đẩy nhanh tiến độ nhé

Thanks & Best Regards
TrungNhan

**Comment by nhanntdl** [comment]
hoàn thành
